export const FETCH_NOMAD_MEMORIES_REQUEST = "FETCH_NOMAD_MEMORIES_REQUEST";
export const FETCH_NOMAD_MEMORIES_SUCCESS = "FETCH_NOMAD_MEMORIES_SUCCESS";
export const FETCH_NOMAD_MEMORIES_FAILURE = "FETCH_NOMAD_MEMORIES_FAILURE";
export const RESET_NOMAD_MEMORIES = "RESET_NOMAD_MEMORIES";
