export const FETCH_LN_REQUEST = "FETCH_LN_REQUEST";
export const FETCH_LN_SUCCESS = "FETCH_LN_SUCCESS";
export const FETCH_LN_FAILURE = "FETCH_LN_FAILURE";
export const RESET_LN = "RESET_LN";

export const FETCH_LC_REQUEST = "FETCH_LC_REQUEST";
export const FETCH_LC_SUCCESS = "FETCH_LC_SUCCESS";
export const FETCH_LC_FAILURE = "FETCH_LC_FAILURE";
export const RESET_LC = "RESET_LC";

export const FETCH_LB_REQUEST = "FETCH_LB_REQUEST";
export const FETCH_LB_SUCCESS = "FETCH_LB_SUCCESS";
export const FETCH_LB_FAILURE = "FETCH_LB_FAILURE";
export const RESET_LB = "RESET_LB";

export const FETCH_LD_REQUEST = "FETCH_LD_REQUEST";
export const FETCH_LD_SUCCESS = "FETCH_LD_SUCCESS";
export const FETCH_LD_FAILURE = "FETCH_LD_FAILURE";
export const RESET_LD = "RESET_LD";

export const FETCH_LT_REQUEST = "FETCH_LT_REQUEST";
export const FETCH_LT_SUCCESS = "FETCH_LT_SUCCESS";
export const FETCH_LT_FAILURE = "FETCH_LT_FAILURE";
export const RESET_LT = "RESET_LT";
