export const STORE_USER = "STORE_USER";
export const STORE_NOMAD = "STORE_NOMAD";
export const STORE_TEMP_NOMAD = "STORE_TEMP_NOMAD";
export const STORE_TOKEN = "STORE_TOKEN";

export const GET_INTERESTS_REQUEST = "GET_INTERESTS_REQUEST";
export const GET_INTERESTS_SUCCESS = "GET_INTERESTS_SUCCESS";
export const GET_INTERESTS_FAILURE = "GET_INTERESTS_FAILURE";

export const GET_FEED = "GET_FEED";
export const GET_OWN_MEMORIES = "GET_OWN_MEMORIES";
export const GET_NOMAD_MEMORIES = "GET_NOMAD_MEMORIES";
export const GET_NOMAD_SUGGESTIONS = "GET_NOMAD_SUGGESTIONS";
export const GET_CARAVAN_SUGGESTIONS = "GET_CARAVAN_SUGGESTIONS";
export const INTERESTS_ERROR = "INTERESTS_ERROR";
export const RESET_NOMAD_MEMORIES = "RESET_NOMAD_MEMORIES";
