export const STORE_USER = "STORE_USER";
export const STORE_NOMAD = "STORE_NOMAD";
export const STORE_TOKEN = "STORE_TOKEN";
export const GET_INTERESTS = "GET_INTERESTS";
export const GET_OWN_MEMORIES = "GET_OWN_MEMORIES";
export const INTERESTS_ERROR = "INTERESTS_ERROR";
