export const FETCH_R_REQUEST = "FETCH_R_REQUEST";

export const FETCH_RI_SUCCESS = "FETCH_RI_SUCCESS";
export const FETCH_RI_FAILURE = "FETCH_RI_FAILURE";

export const FETCH_RO_SUCCESS = "FETCH_RO_SUCCESS";
export const FETCH_RO_FAILURE = "FETCH_RO_FAILURE";
