export const FETCH_NOMAD_FEED_REQUEST = "FETCH_NOMAD_FEED_REQUEST";
export const FETCH_NOMAD_FEED_SUCCESS = "FETCH_NOMAD_FEED_SUCCESS";
export const FETCH_NOMAD_FEED_FAILURE = "FETCH_NOMAD_FEED_FAILURE";
