export const FETCH_SUGGESTIONS_REQUEST = "FETCH_SUGGESTIONS_REQUEST";
export const FETCH_NOMAD_SUGGESTIONS_SUCCESS =
  "FETCH_NOMAD_SUGGESTIONS_SUCCESS";
export const FETCH_NOMAD_SUGGESTIONS_FAILURE =
  "FETCH_NOMAD_SUGGESTIONS_FAILURE";
export const FETCH_CARAVAN_SUGGESTIONS_SUCCESS =
  "FETCH_CARAVAN_SUGGESTIONS_SUCCESS";
export const FETCH_CARAVAN_SUGGESTIONS_FAILURE =
  "FETCH_CARAVAN_SUGGESTIONS_FAILURE";
