export const FETCH_T_REQUEST = "FETCH_T_REQUEST";

export const FETCH_TN_SUCCESS = "FETCH_TN_SUCCESS";
export const FETCH_TN_FAILURE = "FETCH_TN_FAILURE";

export const FETCH_TC_SUCCESS = "FETCH_TC_SUCCESS";
export const FETCH_TC_FAILURE = "FETCH_TC_FAILURE";

export const FETCH_TB_SUCCESS = "FETCH_TB_SUCCESS";
export const FETCH_TB_FAILURE = "FETCH_TB_FAILURE";
