export const FETCH_NOMAD_PROFILE_REQUEST = "FETCH_NOMAD_PROFILE_REQUEST";
export const FETCH_NOMAD_PROFILE_SUCCESS = "FETCH_NOMAD_PROFILE_SUCCESS";
export const FETCH_NOMAD_PROFILE_FAILURE = "FETCH_NOMAD_PROFILE_FAILURE";
